plugins {
    id 'maven-publish'
    id 'com.android.library'
}

android {
    compileSdk = 30
    namespace = "org.megaknytes.decisiontable.ftc"
    defaultConfig {
        minSdk = 24
        //noinspection ExpiredTargetSdkVersion
        targetSdk = 30
        versionCode = 1
        aaptOptions {
            ignoreAssetsPattern = '!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!_*'
        }
    }
    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

publishing {
    publications {
        def configureBasePom = { pub ->
            pub.pom {
                name = 'FTC'
                description = 'FTC Decision Table FTC SDK Integration'
                url = 'http://megaknytes.org'

                developers {
                    developer {
                        id = 'hccsarobotics'
                        name = 'MegaKnytes 11093'
                        email = 'hccsarobotics@gmail.com'
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/MegaKnytes/DecisionTable.git'
                    developerConnection = 'scm:git:ssh://git@github.com:MegaKnytes/DecisionTable.git'
                    url = 'https://github.com/MegaKnytes/DecisionTable#'
                }
            }
        }

        if (System.getenv("CI")) {
            referenceRelease(MavenPublication) {
                groupId = 'org.megaknytes.decisiontable'
                artifactId = 'FTC'

                version = (System.getenv("GITHUB_REF_TYPE") == "tag" ? System.getenv("GITHUB_REF_NAME") : System.getenv("GITHUB_REF_NAME") + "-SNAPSHOT").replace('/', '-')

                configureBasePom(delegate)

                afterEvaluate {
                    from components.release
                }
            }
        } else {
            localRelease(MavenPublication) {
                groupId = 'org.megaknytes.decisiontable'
                artifactId = 'FTC'
                version = "localDeployment-SNAPSHOT"

                configureBasePom(delegate)

                afterEvaluate {
                    from components.release
                }
            }
        }
    }

    repositories {
        maven {
            def releasesRepoUrl = "https://maven.megaknytes.org/releases"
            def snapshotsRepoUrl = "https://maven.megaknytes.org/snapshots"

            url = System.getenv("GITHUB_REF_TYPE") == "tag" ? releasesRepoUrl : snapshotsRepoUrl

            credentials {
                username = System.getenv("MEGAKNYTES_MAVEN_USERNAME")
                password = System.getenv("MEGAKNYTES_MAVEN_PASSWORD")
            }
        }
    }
}

dependencies {
    api project(':Core')

    implementation libs.robotserver
    implementation libs.robotcore
    implementation libs.hardware
    implementation libs.ftccommon
}